server:
  port: 8001  #\u670D\u52A1\u542F\u52A8\u7684\u7AEF\u53E3\u53F7

# Spring\u8BBE\u7F6E
spring:
  application:
    name: springboot_mybatis  #\u5DE5\u7A0B\u540D\u79F0
  datasource: #\u6570\u636E\u6E90\u914D\u7F6E
    driver-class-name: com.mysql.cj.jdbc.Driver #\u9A71\u52A8\u540D\u79F0\uFF08\u6CE8\uFF1Aspringboot2.X\u7248\u672C\u4EE5\u540E\u4F7F\u7528cj.jdbc.Driver\uFF09
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT  #\u6570\u636E\u5E93\u8FDE\u63A5\u5730\u5740\uFF08\u6CE8\u610F\u52A0\u4E0A\u65F6\u533A\uFF09
    username: root  #\u7528\u6237\u540D
    password: root  #\u5BC6\u7801

# mybatis\u8BBE\u7F6E
mybatis:
  type-aliases-package: com.example.pojo  #\u5173\u8054pojo\u5B9E\u4F53\u7C7B
  mapper-locations: classpath:mapper/*Mapper.xml  #\u5173\u8054mapper\u6587\u4EF6\u8DEF\u5F84